### ISSUE TITLE
New save-local version is breaking the package

### ISSUE THREAD

**Issue by drixsonic** [bukinoshita/git-labels-cli#11]
Seems like the new version of `save-local` (`0.2.1`) is breaking this package. I'm receiving:

```bash
TypeError: storage.initSync is not a function
```
`save-local` has a dependency to `node-persist` and with the new release, the version was bumped to `^3.0.0` which is a breaking change. From the change log:

> All the *Sync functions were removed, every operation is now asynchronous

https://www.npmjs.com/package/node-persist#300-change-logs

Unfortunately, this package has a loose dependency on `save-local` (`^0.2.0`), so installing it new will install the breaking dependency.

**Comment by bukinoshita** [comment]
Thanks for reporting! I'm fixing the `save-local` package and then release a version here

**Comment by bukinoshita** [comment]
fixed on `2.0.2`
